name: data-science-cookiecutter
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
    - click
    - coverage
    - awscli
    - flake8
    - python-dotenv>=0.5.1
